<BottomNav@BoxLayout>:
    size_hint_y: None
    height: "50dp"
    spacing: 10
    padding: 20
   
    Button:
        text: "To-Do"
        on_press: app.root.current = "todo"
    Button:
        text: "Flash Cards"
        on_press: app.root.current = "flashCards"
    Button:
        text: "Timer"
        on_press: app.root.current = "timer"
    Button:
        text: "Settings"
        on_press: app.root.current = "settings"

<ToDoScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label: 
            text: "User 1 To Do List"
            height: dp(50)
        ScrollView:
            id: todo_list_scroll
            BoxLayout:
                id: todo_items_container
                orientation: 'vertical'
                size_hint_y: None
                heigth: self.minimum_height
        TextInput:
            id: new_task_input
            hint_text: "Add a new task..."
            size_hint_y: None
            height: dp(40)
        Button:
            text: "Add Task"
            size_hint_y: None
            height: dp(40)
            on_press: app.root.get_screen('todo').addTask()
        BottomNav:
            
<FlashCardsScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label: 
            text: "This is the Flash Cards Screen"
        Button:
            text: "Add card"
            size_hint_x: None
            height: dp(20)
        Button:
            text: "Flip card"
            size_hint_x: None
            height: dp(20)
            
        #Flash Card Deck area
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 1
            padding: 20
            spacing: 10
            
            canvas.before:
                Color:
                    rgba: 0.95, 0.95, 0.95, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [20]
                    
            #Flash Card Image
            Image:
                id: flashcard_image
                source: 
            
        BottomNav:

<TimerScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label: 
            text: "This is the Timer Screen"
        BottomNav:
        
<SettingsScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label: 
            text: "This is the Settings Screen"
        BottomNav:
    
    